# Generated by Django 5.0.3 on 2024-05-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
