# Generated by Django 5.0.3 on 2024-05-31 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
